### PR TITLE
Added install instructions for SPM to README

### PR DESCRIPTION
**Pull request by Enari**
There is support for using the Swift Package Manager but no information about it in the README.

### CODE REVIEW

**Comment by Enari** [comment]
Right, I tried to be as concise as possible. Would it be better to include all parts of a package file? Or would it be enough to add “and add “SwiftSoup” to the dependencies array in your target” ?

**Comment by 0xTim** [comment]
Personally I would be more explicit since SPM is quite new still and people may not know how to use it. But with `...` everywhere rather than a whole manifest. But that’s just my opinion and others may disagree!

**Comment by 0xTim** [comment]
@Enari to be _really_ pedantic I would do something like:

```swift
...
dependencies: [
    .package(url: "https://github.com/scinfu/SwiftSoup.git", from: "1.5.10"),
    ...
],
targets: [
    .target(name: "YourTarget", dependencies: ["SwiftSoup", ...]),
    ...
]
...
```

**Comment by Jinxiansen** [comment]
cool !

**Comment by Enari** [comment]
@0xTim I would prefer not too, I feels like it would take up too much space. This way if you have no other dependencies, it will work fine. If you have other dependencies you probably know how to add multiple.

**Comment by 0xTim** [comment]
Cool, fair enough!

**Comment by 0xTim** [comment]
LGTM

**Comment by scinfu** [comment]
Thank you

**Pull request merged**
